project:
  type: website
  output-dir: docs

website:
  title: "Ian Beilfuss"
  favicon: Logos/tree.png
  google-analytics: G-K33FSX0VCE
  site-url: https://ian88.github.io/
  navbar:
    title: false
    logo: Logos/treeName.png
    right:
      - href: index.qmd
        text: Home
      - href: CartographicProjects.qmd
        text: Cartography
      - href: Photography.qmd
        text: Photography
      - href: blogPosts.qmd
        text: Prague Blog
      - href: resume.qmd
        text: Resume
        target: _blank
        
  page-footer:
    background: light # or `dark`
    left: Copyright 2025, Ian Beilfuss
    right: This website is built with [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/ian88/ian88.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    theme: styles.scss
    mainfont: Raleway
    toc: true
    page-layout: full

editor: visual


#git checkout main
#git pull origin main
#git merge origin/my-new-branch
#git push origin main
